name: Deploy Static Website

# 1) When should pipeline run?
on:
  push:
    branches: ["main"]     # run whenever you push to main branch

# 2) Permissions required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# 3) Only one deployment at a time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # Step 1 — download your repo code into runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 — prepare GitHub Pages environment
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      # Step 3 — upload website files as artifact
      - name: Upload website files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      # Step 4 — deploy website
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4